---
name: conntextual
version: "{{major}}.{{minor}}.{{patch}}"
description: A network-application TUI using textual.
entry: {{entry}}

no_logging_init: true
curses: true

# - "windows-curses; sys_platform == 'win32'"
requirements:
  - runtimepy>=2.6.5
  - textual

dev_requirements:
  - setuptools-wrapper
  - types-setuptools
  - textual-dev

commands:
  - name: ui
    description: "run a user interface for runtimepy applications"
