---
name: conntextual
version: "{{major}}.{{minor}}.{{patch}}"
description: A network-application TUI using textual.
entry: {{entry}}

requirements:
  - runtimepy
  - textual

dev_requirements:
  - setuptools-wrapper
  - types-setuptools
  - textual-dev
