---
name: conntextual
version: "{{major}}.{{minor}}.{{patch}}"
description: A network-application TUI using textual.
entry: {{entry}}

no_logging_init: true

# - "windows-curses; sys_platform == 'win32'"
requirements:
  - psutil
  - runtimepy>=2.12.3
  - textual
  - uvloop
  - plotext
  - numpy

dev_requirements:
  - setuptools-wrapper
  - textual-dev
  - types-psutil
  - types-setuptools

commands:
  - name: client
    description: "attempt to connect a client to a remote session"
  - name: ui
    description: "run a user interface for runtimepy applications"

mypy_local: |
  [mypy-plotext.*]
  ignore_missing_imports = True
